# Generated by Django 2.1.7 on 2020-03-08 00:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('custmanager', '0002_order_products'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='category',
            field=models.CharField(choices=[('NonWoven', 'NonWoven'), ('Woven', 'Woven'), ('Other', 'Other')], max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='products',
            name='date_created',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
