# Generated by Django 2.1.7 on 2020-03-08 01:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('custmanager', '0003_auto_20200307_1943'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='QuantityRolls',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='QuantityY2',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='TotalValue',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='customer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='custmanager.Customer'),
        ),
        migrations.AddField(
            model_name='order',
            name='linenumber',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='ponumber',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='product',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='custmanager.Products'),
        ),
    ]
