# Generated by Django 2.1.7 on 2020-03-08 01:12

from django.db import migrations


class Migration(migrations.Migration):
    atomic = False

    dependencies = [
        ('custmanager', '0005_auto_20200307_2008'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Products',
            new_name='Product',
        ),
        migrations.RenameModel(
            old_name='Tags',
            new_name='Tag',
        ),
    ]
