# Generated by Django 2.1.7 on 2020-03-08 01:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('custmanager', '0007_auto_20200307_2016'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='TotalValue',
        ),
        migrations.AlterField(
            model_name='product',
            name='description',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
