# Generated by Django 2.1.7 on 2020-03-08 01:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('custmanager', '0008_auto_20200307_2028'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='price',
        ),
        migrations.AddField(
            model_name='order',
            name='price',
            field=models.FloatField(null=True),
        ),
    ]
